#!/usr/bin/env bash

set -euo pipefail

mkpassword() {
  local encoder="$1"
  local message="${2:-password}"
  local password=''
  local verification=x

  while [[ $password != "$verification" ]]; do
    echo >&2
    IFS= read -rsp "Enter $message: " password
    echo >&2
    IFS= read -rsp "Repeat $message: " verification
    echo >&2
  done

  printf %s "$password" | $encoder
}

passwordfiles=$(
  nix eval --json \
    "${FLAKE0:?}#nixosConfigurations.${TARGET_HOST:?}.config.users.users" |
  jq --raw-output '
    [ .[].hashedPasswordFile | select(. != null) ]
    | map("/mnt" + .)
    | join(" ")
  '
)

for pfile in $passwordfiles; do
  [ -e "$pfile" ] && continue
  sudo mkdir -p "$(dirname "$pfile")"
  mkpassword 'mkpasswd -s' "password ($pfile)" | sudo tee "$pfile" > /dev/null
done

set -x

sudo mkdir -p /mnt/persist/etc/ssh
sudo cp -a /etc/machine-id /mnt/persist/etc/

sudo nixos-install --flake "$FLAKE0#$TARGET_HOST" --no-root-passwd

sudo cp -ar /mnt/etc/ssh/authorized_keys.d /mnt/persist/etc/ssh/

# Ensure there is a synced local copy of the installation flake
localflake0=/mnt/persist/etc/groundzero
[ -d "$localflake0" ] && sudo rm -rf "$localflake0"
sudo nix flake clone --dest "$localflake0" "$FLAKE0"
sudo chown -R root:users "$localflake0"
