{ config, pkgs, lib, ... }:

let
  # Based on:
  # https://github.com/nix-community/home-manager/issues/1658
  hmListFilesScript =
    let
      files = builtins.concatStringsSep "\n" (
        map (file: file.target) (
          builtins.filter
            (file: !file.recursive)
            (lib.mapAttrsToList (_: file: file) config.home.file)
        )
      );
    in
    pkgs.writeShellScriptBin "my-hm-dotfiles" ''
      # List all dotfiles generated by Home Manager
      cat <<EOF
      ${files}
      EOF
    '';
in
{
  home.packages = [ hmListFilesScript ];
}
